// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:777289691478:android:2009b1fd59fbb69f8766f7',
    messagingSenderId: '777289691478',
    projectId: 'radio-online-518b4',
    databaseURL: 'https://radio-online-518b4.firebaseio.com',
    storageBucket: 'radio-online-518b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:777289691478:ios:2a00d6842dca03f18766f7',
    messagingSenderId: '777289691478',
    projectId: 'radio-online-518b4',
    databaseURL: 'https://radio-online-518b4.firebaseio.com',
    storageBucket: 'radio-online-518b4.appspot.com',
    androidClientId:
        '777289691478-0fiptptp9idg8e9usent90kn8rqnd53e.apps.googleusercontent.com',
    iosClientId:
        '777289691478-38va43b185hlossmvj6egd15mcio5am8.apps.googleusercontent.com',
    iosBundleId: 'com.app.radioonline',
  );
}
